[theme]
primaryColor = "#000000"            # màu chính (nút, tick radio, link)
backgroundColor = "#ffffff"         # nền chính
secondaryBackgroundColor = "#f0f8ff" # nền phụ (sidebar, container)
textColor = "#000000"               # màu chữ
font = "sans serif"